[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.0
datadir=C:/Users/sande/OneDrive/Desktop/teacher-portal-system/teacher-portal-intern-task/backend/.mysql-local/data
port=3307
bind-address=127.0.0.1
skip-networking=0
lower_case_table_names=1
log-error=C:/Users/sande/OneDrive/Desktop/teacher-portal-system/teacher-portal-intern-task/backend/.mysql-local/logs/local.err
pid-file=C:/Users/sande/OneDrive/Desktop/teacher-portal-system/teacher-portal-intern-task/backend/.mysql-local/logs/local.pid
